Repository plotly/dashR, pull requests merged in 2020-02, with the labels that each got.

#168 Support for index page templating
  DESCRIPTION
  NAMESPACE
  R/dash.R
  R/utils.R
  README.md
  man/Dash.Rd
  tests/integration/test_name.py
Labels: enhancement

#176 Add unit tests for index customization
  tests/testthat/test-index.R
Labels: testing

#177 Send status code of 1 when unit tests fail
  .circleci/config.yml
Labels: testing

#175 Dash for R v0.3.0
  .circleci/config.yml
  CHANGELOG.md
  DESCRIPTION
  R/dash.R
  R/utils.R
  man/Dash.Rd
  man/dash-package.Rd
  tests/integration/test_name.py
  tests/testthat/test-index.R
Labels: high priority, parity
